parameters:
  c: 200.0
  m: 12.45
  epsilon: 0.5
  sigma: 0.8
  dth: 0.6
  alpha: 150.0
  eta: 5.0
  dmin: 0.9
  ramp_up_iterations: 50
  raibert_x: 0.1
  raibert_y: 0.1

# Pobs:
#   - [1.5, -0.5]
#   - [2.5,  0.0]
#   - [5.0, -1.0]
#   - [6.0, -1.0]
#   - [6.0,  0.0]

# Pobs_real:
#   - [1.5, -0.5]
#   - [2.5,  0.0]
#   - [5.0, -1.0]
#   - [6.0, -1.0]
#   - [6.0,  0.0]

Pobs:
  - [1,   1.2]
  - [1.3, 0.7]
  - [2.1,  -1]
  - [2.1,  -1.5]
  - [2.1,  -2]
  - [2.1,  -2.5]
  - [2.2,  -0.9]
  - [3.3, 0.5]
  - [3.3, 1.0]
  - [3.3, 1.5]
  - [3.3, 2.0]
  - [3.3, 2.5]
  - [3.7,   0.0]
  - [4.0, -0.5]
  - [4.1, -1.0]

Pobs_real:
  - [1,   1.2]
  - [1.3, 0.7]
  - [2.1,  -1]
  - [2.1,  -1.5]
  - [2.1,  -2]
  - [2.1,  -2.5]
  - [2.2,  -0.9]
  - [3.3, 0.5]
  - [3.3, 1.0]
  - [3.3, 1.5]
  - [3.3, 2.0]
  - [3.3, 2.5]
  - [3.7,   0.0]
  - [4.0, -0.5]
  - [4.1, -1.0]




# Pobs:
#   - [2,  1.2]
#   - [2,  0.5]
#   - [2, -1.0]
#   - [2, -1.5]
#   - [2, -2.0]
#   - [4.2,  0.0]
#   - [4.2, -0.6]
#   - [4.2,  8.5]
#   - [4.2,  8.0]

# Pobs_real:
#   - [2,  1.2]
#   - [2,  0.3]
#   - [2, -1.0]
#   - [2, -1.5]
#   - [2, -2.0]
#   - [4.0,  0.0]
#   - [4.0, -0.6]
#   - [4.2,  8.5]
#   - [4.2,  8.0]